### ISSUE TITLE
may be it better to add explanation popups (title) when hovering above icons button

### ISSUE THREAD

**Issue by shootermv** [chess-mazes/chess-mazes#13]
<img width="350" alt="Screen Shot 2023-04-21 at 18 07 36" src="https://user-images.githubusercontent.com/1336862/233671124-0d732257-9250-4b50-80a4-5d1d2fd9dba9.png">

**Comment by lidor12456** [comment]
PR opened

**Comment by shootermv** [comment]
may ti can be good to ad link to the PR?

**Comment by lidor12456** [comment]
> may ti can be good to ad link to the PR?

https://github.com/chess-mazes/chess-mazes/pull/14

**Comment by eternaleclipse** [comment]
Merged and closed, thanks 🙂
