### ISSUE TITLE
Prevent users from winning in the same move that they make mistake

### ISSUE THREAD

**Issue by eternaleclipse** [chess-mazes/chess-mazes#17]

**Comment by dvirberlo** [comment]
It seem that you solved it [here](https://github.com/chess-mazes/chess-mazes/commit/49296bdcb0a985ee78a97c6e08df6265163480d8#diff-2c00471d025fbd1d72fdb0e8951483e7c67df57a91a97226b7379defecf2e471).

You just forgot the add `return;` to prevent the function to continue to the win check...

**Comment by eternaleclipse** [comment]
Fixed in https://github.com/chess-mazes/chess-mazes/pull/37
