### ISSUE TITLE
Incorrect puzzle number display

### ISSUE THREAD

**Issue by eternaleclipse** [chess-mazes/chess-mazes#24]
Internally, puzzle numbers are `0` .. `n`.
On the display side, though, they should appear as `1` .. `n+1`.

i.e. Currently the first puzzle appears as "Chess Mazes #0".

**Comment by lidor12456** [comment]
PR opened

**Comment by lidor12456** [comment]
> PR opened

https://github.com/chess-mazes/chess-mazes/pull/30

**Comment by eternaleclipse** [comment]
merged
