### ISSUE TITLE
Convert and encforce line endings to LF

### ISSUE THREAD

**Issue by dvirberlo** [chess-mazes/chess-mazes#26]
I ran git diff and noticed that there are many diffs that are just CRLF -> LF and vice versa. To ensure consistency across all platforms, we should convert all line endings to LF.

We can use .editorconfig to enforce line endings across all platforms. 
Here’s an example `.editorconfig` file that you can use (including few more standart configurations):
```.editorconfig

# https://EditorConfig.org

root = true

[*]
charset = utf-8
end_of_line = lf
indent_style = space
indent_size = 2
insert_final_newline = true
trim_trailing_whitespace = true
```

**Comment by eternaleclipse** [comment]
Merged #29
