### ISSUE TITLE
Apply for Vercel open-source sponsorship

### ISSUE THREAD

**Issue by eternaleclipse** [chess-mazes/chess-mazes#49]
https://vercel.com/guides/can-vercel-sponsor-my-open-source-project

**Comment by eternaleclipse** [comment]
Added Vercel banners as per the sponsorship criteria, and sent an email to [sponsorships@vercel.com](mailto:sponsorships@vercel.com).

**Comment by dvirberlo** [comment]
The banner, in its currnet state, takes up a lot of vertical space.
Maybe the margin and border can be removed?

**Comment by eternaleclipse** [comment]
Hmm, the border is quite necessary for dark mode.
I don't have a problem with the banner taking up vertical space if it's at the bottom anyway :)

**Comment by eternaleclipse** [comment]
Update:
They haven't replied to my email yet.
Pro trial ends in 4 days and free plan ("Hobby") doesn't allow Github organizations as far as I can tell.

Anyone know someone at Vercel? 😄

**Comment by eternaleclipse** [comment]
They have responded on email that they won't be able to sponsor our project, without further explanation (Which seems strange to me, since the project is open source and I believe we have adhered to the guidelines on their sponsorship page).

Either way, perhaps I misunderstood the difference between the plans but for now the free plan works - Closing.
