### ISSUE TITLE
Piece move animations

### ISSUE THREAD

**Issue by eternaleclipse** [chess-mazes/chess-mazes#50]

**Comment by ETtestim** [comment]
I think this could be challenging depends on the animation we want. as every move you make creates a new board meaning we render the entire board every time.

**Comment by eternaleclipse** [comment]
I've merged the PR, thanks. I'm closing the issue, but still noting that we will need to consider how to handle animations better in the future. Specifically:
- Variety of animations in different situations (Move, victory, mistake, wrong piece etc)
- Different animations (possibly tied to themes)
- Whether to use a library such as Mo.js
