### ISSUE TITLE
Background music

### ISSUE THREAD

**Issue by eternaleclipse** [chess-mazes/chess-mazes#53]
Background music can add a nice atmosphere to the game 🎵

For now, let's use these two tracks:
https://freemusicarchive.org/music/Strobotone/game-and-broadcast-music/medieval-theme-01/
https://freemusicarchive.org/music/Strobotone/game-and-broadcast-music/medieval-theme-02-1/

They are licensed CC-BY-ND (attribution is required and derivatives are not allowed).

At least two buttons are necessary:
- Music On / Off
- Next Track

When the music is turned on, the current song will play from the start, and when it ends, the game will will Autoplay the next track. When the playlist ends, it should cycle back to the first track. ("Off" and "Next track" are self-explanatory).

**Comment by ETtestim** [comment]
please add description to this issue.
Do you have a specific sound?

**Comment by eternaleclipse** [comment]
Thanks for your interest in this issue! I've updated the description.

**Comment by ShahafPinto** [comment]
I would like to work on this - Please assign this issue to me

**Comment by eternaleclipse** [comment]
#80 done!
