### ISSUE TITLE
Maze number in title doesn't match url

### ISSUE THREAD

**Issue by ETtestim** [chess-mazes/chess-mazes#60]
Needs to decide if we start at zero or at one?
![image (3)](https://user-images.githubusercontent.com/109076747/234864503-e257918c-c461-4eac-abf0-d672e232ac21.png)

**Comment by eternaleclipse** [comment]
Hey! Thanks for the bug report. The internal representation (In the code, `puzzleNum` etc) should start at 0, and the display representation (In UI elements such as title, URL - everything the user sees and interacts with directly) to start at 1.

If you feel like fixing this, I can assign the issue to you.

**Comment by eternaleclipse** [comment]
#68
