### ISSUE TITLE
Change board renderer to use canvas (Instead of divs)

### ISSUE THREAD

**Issue by eternaleclipse** [chess-mazes/chess-mazes#8]
Currently, the board renderer just loops through the board state and creates a `div` for every square.
https://github.com/eternaleclipse/chess-mazes/blob/d86f583b12915c8aaf3ed4642944262d6a18b90e/gameView.js

Ideally, we want this to use the Canvas API to draw the board to a `canvas` element.
This would also require changing the input handling (click, drag-and-drop) to work with the new `canvas` element.

**Comment by dvirberlo** [comment]
What are the advantage of canvas over the current solution?
I just want to point out a possible disadvantage:
Bigger bundle size, to include some drawing and input recognition for canvas.

**Comment by eternaleclipse** [comment]
Good point. The main reasons I wanted to move to canvas:
1. There is a small delay when the player moves. This is more apparent on mobile. I believe this is due to the fact that DOM changes are CPU intensive, and I think using canvas can easily get seamless, 60 fps rendering with very little input lag. However, when testing now, it seems to be insignificant.
2. The use of canvas will ensure that the game is rendered the same way on every device. However, this may be a disadvantage in itself, because the use of flex and responsive design makes the game appear better on different resolutions.

In my view, there are equal-ish pros and cons to both approaches. Given that the current solution works well, there's no strong reason to switch. If you feel the same way about this, we can close the issue.

**Comment by dvirberlo** [comment]
Closing it for now, then.
If, in the future we would want to add, say, animations and more specific styling and decoration- we will need to reconsider this.
