### ISSUE TITLE
Add frontend dependencies to package.json, Webpack, and build / publish

### ISSUE THREAD

**Issue by eternaleclipse** [chess-mazes/chess-mazes#9]
Although this is currently a frontend-only project, it could still use package management from npm (currently the project is only using SweetAlert2 - as it matures and more libraries are added, using npm will make things easier). Frontend package installation needs to be managed by npm, and references to libraries (currently only SweetAlert2) need to be changed to point to `node_modules`. 

There is a problem though: Since the package dependencies will not be hosted on the GitHub repo directly, we will need a separate build and publish steps. This can be automated using Webpack and the `gh-pages` npm package.

**Comment by dvirberlo** [comment]
I think it has been solve when we migrated to react and Vite
